url: "quinnel.github.io"
baseurl:
host: 0.0.0.0
port: 4000

# Site Settings
title: Quinn Liu
description: "Personal page."
keywords: "Computer science, website, web design, software engineer,"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.md"]
