url: "quinnel.github.io"
baseurl:

# Site Settings
title: Quinn Liu
description: "Personal page."
keywords: "Computer science, website"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.md"]
